language: ruby
bundler_args: --without deployment
before_install:
    - gem install bundler
    - npm install phantomjs-prebuilt

script: rake travis
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
